spring:
  application:
    name: Gym_Integrational_Testing

server:
  ssl:
    enabled: true
    key-store: classpath:myCertificate.jks
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
    trust-store: classpath:myCertificate.jks
    trust-store-type: PKCS12
    trust-store-password: ${TRUST_STORE_PASSWORD}
  port: 8095
