spring:
  application:
    name: GYM-TRAINER-WORKLOAD
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongodb:27017/${MONGODB_DB_NAME}?authSource=admin
      database: ${MONGODB_DB_NAME}

server:
  ssl:
    enabled: true
    key-store: classpath:myCertificate.jks
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
    trust-store: classpath:myCertificate.jks
    trust-store-type: PKCS12
    trust-store-password: ${TRUST_STORE_PASSWORD}
  port: 8080

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{X-Transaction-Id}] [%thread] %-5level %logger{36} - %msg%n"

rabbitmq:
  host: rabbitmq
  port: 5672
  username: ${RABBITMQ_USER}
  password: ${RABBITMQ_PASSWORD}
  trainer-workload-queue-name: trainerWorkloadQueue
  retry-time-ms: 5000
