services:
  GYM-TRAINER-WORKLOAD:
    image: gym-trainer-workload
    container_name: gym-trainer-workload
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - JAVA_OPTS="-Djavax.net.ssl.keyStore=/app/resources/myCertificate.jks -Djavax.net.ssl.keyStorePassword=${KEY_STORE_PASSWORD} -Djavax.net.ssl.trustStore=/app/resources/myCertificate.jks -Djavax.net.ssl.trustStorePassword=${TRUST_STORE_PASSWORD}"
    networks:
      gym-network:
        ipv4_address: 172.18.0.6
    volumes:
      - ./src/main/resources/myCertificate.jks:/app/resources/myCertificate.jks

networks:
  gym-network:
    external: true
